// ─── Word lists by length ──────────────────────────────────────────────────────

const WORDS_BY_LENGTH = {
  4: [
    'ABLE','BACK','CALM','DARK','EASY','FACE','GAIN','HALF','IDEA','JUST',
    'KEEP','LAST','MADE','NEED','ONLY','PART','QUIT','REAL','SAFE','TAKE',
    'USED','VERY','WANT','YEAR','ZERO','ALSO','BEST','CARE','DONE','EVEN',
    'FIND','GIVE','HAVE','INTO','JOIN','KNOW','LIKE','MAKE','NEXT','OPEN',
    'PLAN','RACE','SELL','TELL','UPON','VIEW','WALK','EXAM','YOUR','ZONE',
    'BOLD','CORN','DAWN','EDGE','FARM','GLOW','HOPE','IRON','JUMP','KICK',
    'LAMP','MELT','NEWS','ONCE','PAIN','QUIZ','RING','SHIP','TREE','UNIT',
    'VOID','WIND','AXIS','BONE','COOK','DEER','ECHO','FISH','GRIP','HEAT',
    'IRIS','JADE','KEEN','LION','MINT','NAIL','OATH','POOL','ROPE','SNOW',
    'TRAM','UGLY','VAST','WARD','YELL','ZINC','ARCH','BUZZ','CLAP','DRUM',
  ],
  5: [
    'ABOUT','ABOVE','AGREE','ALLOW','APPLE','BEACH','BLACK','BLOOD','BOARD','BONUS',
    'BRAVE','BREAK','BRING','BROWN','BUILD','CABLE','CARRY','CATCH','CHAIN','CHAIR',
    'CHASE','CHEAP','CHECK','CHILD','CLAIM','CLEAN','CLEAR','CLOCK','CLOSE','CLOUD',
    'COACH','COLOR','COUNT','COURT','COVER','CRACK','CRAFT','CREAM','CRIME','CROSS',
    'CROWD','CRUSH','CURVE','DAILY','DANCE','DEATH','DEPTH','DIRTY','DOUBT','DRAFT',
    'DRAIN','DRAMA','DREAM','DRESS','DRINK','DRIVE','EARLY','EARTH','EIGHT','ENEMY',
    'ENTER','ERROR','EXACT','EXTRA','FANCY','FAULT','FEAST','FEVER','FIELD','FIFTH',
    'FIGHT','FINAL','FIRST','FIXED','FLAME','FLASH','FLOOD','FLOOR','FOCUS','FORCE',
    'FOUND','FRAME','FRESH','FRONT','FRUIT','GHOST','GIANT','GLASS','GLOBE','GRACE',
    'GRAIN','GRAND','GRASS','GRAVE','GREAT','GREEN','GROUP','GROWN','GUARD','GUESS',
    'GUEST','GUIDE','GUILT','HEART','HEAVY','HOUSE','HUMAN','HUMOR','IDEAL','IMAGE',
    'ISSUE','JUDGE','JUICE','KNIFE','LARGE','LASER','LATER','LAUGH','LAYER','LEARN',
    'LEGAL','LEVEL','LIGHT','LIMIT','LOCAL','LOOSE','LOWER','LUCKY','LUNCH','MAGIC',
    'MEDIA','MIXED','MODEL','MONEY','MONTH','MORAL','MOUTH','MUSIC','NEVER','NIGHT',
    'NOISE','NORTH','NURSE','OFFER','OFTEN','OLIVE','ORDER','OUTER','OWNER','PAINT',
    'PANIC','PAPER','PAUSE','PEACE','PHONE','PHOTO','PIECE','PILOT','PITCH','PIZZA',
    'PLACE','PLAIN','PLANE','PLANT','PLATE','POINT','POWER','PRESS','PRICE','PRIDE',
    'PRIME','PRINT','PRIZE','PROOF','PROVE','PULSE','QUEEN','QUEST','QUICK','QUITE',
    'QUOTE','RAISE','RANCH','RANGE','RAPID','REACH','READY','REALM','RELAX','RIGHT',
    'RISKY','RIVAL','RIVER','ROBOT','ROUGH','ROUND','ROYAL','SAUCE','SCALE','SCENE',
    'SCOPE','SCORE','SENSE','SERVE','SEVEN','SHADE','SHAKE','SHAME','SHAPE','SHARE',
    'SHARP','SHIFT','SHIRT','SHOCK','SHORT','SHOOT','SHOUT','SIGHT','SINCE','SKILL',
    'SLEEP','SLIDE','SMOKE','SOLAR','SOLVE','SORRY','SPACE','SPEAK','SPEED','SPEND',
    'SPLIT','SPORT','STAFF','STAKE','STAND','START','STATE','STEAM','STICK','STILL',
    'STOCK','STONE','STORE','STORM','STORY','STUDY','STUFF','STYLE','SUPER','SWEET',
    'SWORD','TABLE','TASTE','TEACH','TEETH','THEME','THICK','THING','THINK','THOSE',
    'THREE','THROW','TIGHT','TITLE','TODAY','TOTAL','TOUCH','TOUGH','TOWER','TRACK',
    'TRADE','TRAIL','TRAIN','TREAT','TRIAL','TRUCK','TRUST','TRUTH','TWICE','UNCLE',
    'UNION','UNTIL','UPPER','UPSET','URBAN','VALID','VALUE','WATCH','WATER','WHERE',
    'WHICH','WHILE','WHITE','WHOLE','WRITE','WRONG','YACHT','YOUNG',
  ],
  6: [
    'CASTLE','BRIDGE','FLIGHT','GARDEN','HANDLE','ISLAND','JOYFUL','KETTLE',
    'LAUNCH','MARKET','NATURE','ORANGE','PALACE','RABBIT','SILVER','TRAVEL',
    'UNIQUE','VIOLET','WINTER','YELLOW','ZIPPER','BEFORE','CANDLE','FAIRLY',
    'GATHER','HEALTH','IMPACT','KITTEN','LIVELY','MIRROR','NOTICE','PEOPLE',
    'REALLY','STROLL','TENDER','USEFUL','VALLEY','WARMTH','ACROSS','BATTLE',
    'DANCER','ENERGY','FABRIC','GRAVEL','HARBOR','INSECT','JUNGLE','KNIGHT',
    'LIQUID','MEADOW','NICKEL','OXYGEN','PARENT','RACING','SOCIAL','TIMING',
    'UNITED','VISION','WEALTH','BASKET','CARROT','DANGER','EASILY','FENDER',
    'GLIDER','HOLLOW','KEYPAD','LETTER','MINGLE','NORMAL','OYSTER','PLANET',
    'RHYTHM','SPORTS','THREAD','UPWARD','VICTIM','WOODEN','CIRCLE','DIRECT',
    'EFFORT','FINGER','HAPPEN','INTENT','JASPER','MUSCLE','NEARLY','OPENED',
    'PENCIL','SIMPLE','TALENT','URGENT','VELVET','WANDER','ANIMAL','BEAUTY',
    'CHERRY','DIVIDE','ESCAPE','FATHER','GOLDEN','HUMBLE','INSANE','KINDLY',
    'LINGER','MELLOW','NOODLE','OBTAIN','PILLOW','RESCUE','SETTLE','TICKLE',
    'VACUUM','WEEKLY','ADMIRE','BELONG','COPPER','DAMAGE','EDITOR','FORMAL',
    'GINGER','HONEST','IGNITE','JAGUAR','LIZARD','MENTAL','NATION','OFFSET',
    'ACCEPT','BOTTLE','CLEVER','DEFINE','ERRAND','FLAVOR','GLANCE','HUNGER',
    'INVENT','JUMBLE','KEEPER','LOCATE','MANAGE','NEARBY','ORPHAN','POLISH',
    'RANDOM','SENDER','TEMPLE','VERIFY','WHOLLY','ADVICE','BOUNCE','CORNER',
    'DEFEND','FROZEN','GOBLIN','INVITE','JOYOUS','KNIVES','MARGIN','NEEDLE',
    'OUTFIT','PARTLY','REWARD','SIGNAL','TARGET','UNLOCK','WEIGHT','ABSORB',
    'BARREL','CLOUDY','DEPLOY','EVOLVE','FIGURE','GLOBAL','INTACT','JINGLE',
    'LOVELY','MARBLE','ORIGIN','PURPLE','RISING','SMOOTH','THRONE','UNFOLD',
    'VESSEL','WAVING','ACTIVE','BANNER','COMMON','DEFEAT','FRIGHT','GREASE',
    'HUNTER','INSIST','JUNIOR','LISTEN','MODEST','NARROW','PACKET','RITUAL',
    'STOLEN','TRADED','VENDOR','AFFECT','BUDGET','CHANGE','DOUBLE','EXPOSE',
    'FOSTER','GENTLE','HAPPEN','JESTER','KERNEL','MIDDLE','NUMBER','POWDER',
    'REFORM','SINGLE','TURTLE','UNSEEN','WASTED','BINARY','DAMAGE','EXCESS',
    'FORGET','HAMMER','INDOOR','LOCKET','NATIVE','PEBBLE','REMAIN','SPOKEN',
    'TESTED','WAFFLE','ALMOST','BOTHER','DRIVEN','EXPECT','FROZEN','HEIGHT',
    'ORANGE','SCARCE','TROPHY','UNLIKE','VANISH','ACTUAL','BYPASS','DETAIL',
    'GROUND','INDOOR','JIGSAW','KILLER','MEMORY','NAPKIN','PILLOW','RATING',
    'SCREAM','STRICT','UNTOLD','VISUAL','WORSEN','ACCUSE','CLOSER','DINNER',
    'FELINE','GOSSIP','INFORM','JOCKEY','LEGEND','MUSTER','PEPPER','REDUCE',
    'SENIOR','TABLES','BROKEN','CURFEW','DECODE','EMPIRE','FACTOR','GROWTH',
    'HELPER','INSULT','LAYOUT','MIGHTY','NIMBLE','OLDEST','PROVEN','SCHOOL',
  ],
  7: [
    'ABILITY','ADVANCE','AIRPORT','ALREADY','AMAZING','ANCIENT','ANOTHER','ARCHIVE',
    'ARTICLE','AVERAGE','AWESOME','BALANCE','BECAUSE','BELIEVE','BENEFIT','BETWEEN',
    'CAPTAIN','CENTRAL','CERTAIN','CHAPTER','CHARITY','CLASSIC','CLIMATE','COLLECT',
    'COMPANY','COMPLEX','CONCEPT','CONCERN','CONDUCT','CONFIRM','CONNECT','CONTENT',
    'CONTEXT','CONTROL','CORRECT','COUNTRY','CURRENT','DECLARE','DECIDED','DEFAULT',
    'DEFICIT','DELIVER','DESPITE','DEVELOP','DISCUSS','ELEMENT','ENHANCE','EPISODE',
    'EXAMPLE','EXCITED','EXPLORE','EXPRESS','EXTREME','FAILURE','FASHION','FEATURE',
    'FEELING','FICTION','FINALLY','FORWARD','FREEDOM','GENERAL','GETTING','HISTORY',
    'HOLIDAY','HORIZON','HOWEVER','HUNDRED','IMAGINE','IMPROVE','INCLUDE','INSTEAD',
    'INVOLVE','KITCHEN','KNOWING','LEADING','LEARNED','LEAVING','LIMITED','MACHINE',
    'MAXIMUM','MESSAGE','MILLION','MINIMUM','MISSION','MORNING','NOTHING','OBVIOUS',
    'OFFICER','OPINION','PASSION','PATIENT','PATTERN','PERHAPS','PICTURE','PLASTIC',
    'POPULAR','PORTION','PROBLEM','PROCESS','PRODUCT','PROGRAM','PROJECT','QUALIFY',
    'QUALITY','REALITY','RECEIVE','RELATED','RELEASE','REQUIRE','RESPECT','RESULTS',
    'REVERSE','SCIENCE','SERVICE','SETTING','SEVERAL','SHELTER','SIMILAR','SPECIAL',
    'STATION','STUDENT','SUCCESS','SUGGEST','SURFACE','TACTICS','TEACHER','THROUGH',
    'TONIGHT','TOURISM','TOWARDS','TRAFFIC','TROUBLE','TRUSTED','TYPICAL','UNKNOWN',
    'UNUSUAL','USUALLY','VARIOUS','VERSION','VILLAGE','VISITED','WEEKEND','WHETHER',
    'WITHOUT','WORKING','WRITTEN','ACCOUNT','ACHIEVE','ACQUIRE','ADAPTED','ADDRESS',
    'ALTERED','AMAZING','ARRANGE','ATHERS','BANKING','CHAPTER','CHARGED','CHECKED',
    'CLAIMED','CREATED','CULTURE','DAMAGES','DIGITAL','DOLLARS','DRAWING','EASTERN',
    'ECONOMY','ELECTED','ENGLISH','ENTERED','EXAMINE','FARMING','FEDERAL','FINGERS',
    'FITNESS','FOREIGN','GROWING','HANDLED','HOUSING','HUNTING','IMPACTS','INVITED',
    'JOGGING','JUSTICE','KEEPING','LEADING','LEARNED','LEATHER','LOCATED','LOOKING',
    'MANAGED','MATCHES','MEASURE','MEDICAL','MEMBERS','METHODS','NEITHER','NETWORK',
    'OFFERED','ORDERED','OUTSIDE','PAINTED','PARENTS','PARKING','PERCENT','PERFECT',
    'PERFORM','PERSONS','PLACING','PLEASED','POINTED','PRIVATE','PROCESS','PROTECT',
    'PROVIDE','PURPOSE','QUARTER','RAISING','REACHED','READING','REMAINS','REMOVED',
    'REPLACE','RESPECT','RETURNS','RUNNING','SAVINGS','SCORING','SECURED','SENDING',
    'SERIOUS','SERVING','SISTERS','SITTING','SKILLED','SMALLER','SOLVING','SPEAKER',
  ],
  8: [
    'ABSOLUTE','ACTUALLY','ADVANCED','ALTHOUGH','ANYWHERE','APPROACH','APPROVAL',
    'ARGUMENT','ATTITUDE','AUDIENCE','BECOMING','BALANCED','BENEFITS','BIRTHDAY',
    'BUSINESS','CALENDAR','CAPACITY','CATEGORY','CHANGING','CHILDREN','CHOOSING',
    'CREATING','CREATIVE','CRIMINAL','DATABASE','DECISION','DELIVERY','DESCRIBE',
    'DESIGNED','DIALOGUE','DISASTER','DISCOVER','DISTINCT','DOCUMENT','DOWNLOAD',
    'ECONOMIC','ELECTRIC','EVERYONE','EVIDENCE','EXERCISE','EXPECTED','FOOTBALL',
    'FUNCTION','GENERATE','GREATEST','HEADLINE','HOSPITAL','IDENTIFY','INCREASE',
    'INDUSTRY','INFINITE','INTEREST','INTERVAL','INVESTED','INVOLVED','LOCATION',
    'MARRIAGE','MEDICINE','MEMORIAL','MINORITY','MOVEMENT','MULTIPLE','NATIONAL',
    'NEGATIVE','NORTHERN','OBSERVED','OCCASION','ORIGINAL','POSITIVE','POSSIBLE',
    'PREPARED','PREVIOUS','PRIORITY','PROBABLY','PURCHASE','QUESTION','RATIONAL',
    'REALIZED','RECENTLY','RECOVERY','RELEASED','RESEARCH','RESOURCE','RESPONSE',
    'REVIEWED','SEASONAL','SECURITY','SELECTED','SEPARATE','SOLUTION','SPENDING',
    'STRAIGHT','STRATEGY','STRENGTH','STUDENTS','STUDYING','SUPERIOR','TOGETHER',
    'TRANSFER','TRAINING','UNCOMMON','VACATION','VALUABLE','PHYSICAL','WHATEVER',
    'WHENEVER','YOURSELF','ABSOLUTE','ACCEPTED','ACCURATE','ACHIEVED','ACQUIRED',
    'ADJUSTED','AFFECTED','AGENCIES','AIRCRAFT','ALTHOUGH','ANALYSIS','ANSWERED',
    'APPLYING','ASSESSED','ASSIGNED','ASSISTED','ATHLETES','ATTENDED','BALANCED',
    'BASEBALL','BECOMING','BELIEVED','BIRTHDAY','BOUNDARY','BREAKING','BROTHERS',
    'BROTHERS','BUILDING','CALENDAR','CAMPAIGN','CAPACITY','CAPTURED','CARELESS',
    'CENTERED','CHANGING','CHAPTERS','CHARGING','CHEMICAL','CHOOSING','CLIMBING',
    'COMBINED','COMEBACK','COMPILED','COMPLETE','COMPUTED','CONCERNS','CONCRETE',
    'CONGRESS','CONNECTS','CONSIDER','CONTAINS','CONTRAST','CONTROLS','COVERING',
    'CRIMINAL','CULTURAL','CURRENCY','CUSTOMER','DATABASE','DAUGHTER','DECISION',
    'DECLARED','DEFEATED','DEFINITE','DELIVERY','DEPARTED','DETAILED','DIRECTED',
    'DISASTER','DOMESTIC','DOMINANT','DOUBLING','DRAWBACK','EARNINGS','EDUCATED',
    'ELECTION','ELEVATED','EMERGING','EMPLOYED','ENCLOSED','ENFORCED','ENTERING',
    'EQUIPPED','ESTIMATE','EVALUATE','EVIDENCE','EXCHANGE','EXTENDED','EXTERNAL',
  ],
};

// Keep the 6-letter list as default export for backward compat
export const WORD_LIST = WORDS_BY_LENGTH[6];

export function getRandomWord(length = 6) {
  const list = WORDS_BY_LENGTH[length] || WORDS_BY_LENGTH[6];
  return list[Math.floor(Math.random() * list.length)];
}

export function isValidWord(word, length) {
  const targetLength = length || word.length;
  return word.length === targetLength && /^[A-Za-z]+$/.test(word);
}

// In-memory cache so the same word isn't looked up twice
const _dictCache = {};

/**
 * Returns:
 *   'valid'   — confirmed real English word
 *   'invalid' — confirmed not a word
 *   'unknown' — network error / timeout (caller decides how to handle)
 */
export async function checkDictionaryWord(word) {
  const key = word.toUpperCase();
  if (key in _dictCache) return _dictCache[key];

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 4000);

  try {
    const res = await fetch(
      `https://api.dictionaryapi.dev/api/v2/entries/en/${word.toLowerCase()}`,
      { signal: controller.signal }
    );
    clearTimeout(timer);
    const result = res.ok ? 'valid' : 'invalid';
    _dictCache[key] = result;
    return result;
  } catch {
    clearTimeout(timer);
    return 'unknown'; // network unavailable or timed out
  }
}
